### ISSUE TITLE
WEB, WAS 확인 + 테스트서버를 구축한다.

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#1]
http://www.xest.kr/product/resinweb.jsp?a=web

**Comment by mozodev** [comment]
ec2 램 2GB 하드는 30GB면 충분하지 않을까...
램 좀 부족하면 swap 좀 잡으면 될 듯 하고요.
일단 생성하고 검색엔진쪽 계정 생성해서 sudoer 주고 하면 될 듯 합니다.
