### ISSUE TITLE
사진아카이브 - 안내 및 연결

### ISSUE THREAD

**Issue by sda17dev** [sda17dev/sda-web#105]
사진아카이브 - 사진기록 전체 검색 연결
레거시 페이지 연계 및 안내 / HTML 접근해서 변경될 페이지 안내 
2월 ~ 5월

**Comment by woonjjang** [comment]
[탐색][검색]을 연결한다. 
검색 - 썸네일 프리뷰를 보여준다. 
기존에 갖고 있던 태그 DB데이터는 태그로 연결해서 기록이 연결되어 보이도록 지원한다. (별도로 기록 세부에서 태그를 지원하는 것은 피하는게 좋을 듯 함.)

https://app.moqups.com/ddevc2Sl0I/edit/page/a2955de15
https://app.moqups.com/ddevc2Sl0I/edit/page/a69ca0b42
https://app.moqups.com/ddevc2Sl0I/edit/page/a381a6a53

**Comment by woonjjang** [comment]
/html-v2/53_collection_view_new.html
