### ISSUE TITLE
스키마 변경분 반영 및 입수

### ISSUE THREAD

**Issue by mozodev** [sda17dev/sda-web#114]
- [x] 스키마 반영 - 테이블명세서 20190124
- [x] 입수 - 20190125 data jsons - files 3.1GB

**Comment by woonjjang** [comment]
# REPORT-20190125 입수 데이터

CL_CLASS_20190125.json
117 => 118 (+1)

CL_CLASS_CON_20190125.json
72 => 73 (+1)

RC_AGGREGATION_20190125.json
4214 => 4254 (+40)

RC_AGGREGATION_CON_20190125.json
4203 => 4243 (+40)

RC_ITEM_20190125.json
106740 => 106877 (+137)

RC_ITEM_CON_20190125.json
106740 => 106877 (+137)

RC_COMPONENT_20190125.json
113130 => 113284 (+154)

RC_ITEM_COMPONENT_20190125.json
113130 => 113284 (+154)

CL_CLASSIFY_RECORDS_RESULT_20190125.json
105200 => 105243 (+43)

## 필드 추가

- CL_CLASS +4
- CL_CLASS_CON +7
- RC_AGGREGATION_CON +1
- RC_COMPONENT +4
