### ISSUE TITLE
[회원] 카카오톡, 네이버 로그인(SFR-029-04)

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#117]
-이메일 입력만 -> 뉴스레터나 소식 발송(최소 정보)
- 개인정보를 거의 등록하지 않고 -> 다운로드, 기록보기, 즐겨찾기 등 모든 기능들을 제공할 수 있음. 
- 서울시에서 개인정보를 확인해야만 전달할 수 있는 참여, 교육프로그램, 모집 시에 로그인 정보에 추가적으로 개인 정보를 입력해서 반복해서 입력하지 않도록 동의하는 프로세스를 만들어서 (교육, 참여 팀에서 사용할 수 있도록 함.)
- 페이스북 로그인 (도메인 확보시)

**Comment by woonjjang** [comment]
https://app.moqups.com/ddevc2Sl0I/edit/page/a5b166335

**Comment by woonjjang** [comment]
기본 서비스 컬러 사용해서 / 회원가입 로그인에 버튼 2개씩 추가 부탁드려요 ~

**Comment by css3studio** [comment]
작업하여 푸시하였습니다.

/html-2018/60_member_join.html
/html-2018/61_member_login.html

**Comment by woonjjang** [comment]
디자인 스타일 수정 확인
