### ISSUE TITLE
[메인] 푸터개선 및 기본 썸네일 수정

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#119]
- 뉴스 / 칼럼 / 연구보고 기본 썸네일 변경 및 적용
- 메인 부분 퍼블리싱 변경사항 반영(Body / Footer)

**Comment by woonjjang** [comment]
https://ufofactory.atlassian.net/browse/JJ-443

**Comment by css3studio** [comment]
수정완료
