### ISSUE TITLE
서울기록원 Git 계정으로 이동 / 인수인계

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#132]
- sdaweb 공개
- sda-dev-docs 공개
- java wrapper 테스트 - 공개
- php wrapper 테스트 - 공개

**Comment by woonjjang** [comment]
@mozodev 옮기기 적절한 시점을 알려주시면 좋을 듯

**Comment by woonjjang** [comment]
@mozodev 도큐사우르스 이전 먼저 해주시면 감사하겠습니다. 매뉴얼 써서 전달할께요.

**Comment by sda17dev** [comment]
이메일 인증해야 레포지토리를 만들 수 있네요..

**Comment by mozodev** [comment]
이메일 인증해야 레포지토리를 만들 수 있네요 ㅎ 내일 진행할께요.
