### ISSUE TITLE
카테고리 메뉴 현재 페이지 항목 하이라이팅

### ISSUE THREAD

**Issue by css3studio** [sda17dev/sda-web#135]
http://52.79.195.15/posts
모조님 여기 오른쪽에 카테고리 메뉴에서 
현재 페이지에 해당하는 카테고리의  li 에 class="on" or "current"부탁합니다

**Comment by woonjjang** [comment]
디자인이 나왔나요 ?

**Comment by css3studio** [comment]
JJ454로 용님이 이슈등록했구요. 거기에 이미지 등록해 줬습니다
