### ISSUE TITLE
서울시 GNB 컬러 변경

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#16]
[서울시 공통GNB가이드_최종.pdf](https://github.com/sda17dev/sda-web/files/1557783/GNB._.pdf)

- 디자인과 동일하게 회색값 적용
- width 값 1200px이상일 때 대응
- 최종 수정후 ID값 발급 받아서 교체

**Comment by css3studio** [comment]
- 디자인과 동일하게 회색값 적용 ：완료

**Comment by css3studio** [comment]
"width 값 1200px이상일 때 대응"은 어떤 경우를 말하는 것인지요?

**Comment by woonjjang** [comment]
저희쪽 gnb는 1200이상이어도 반응형으로 늘어나는데, 서울시 GNB는 최대 사이즈가가 1200이어서 더 늘어나지 않아 서울시 로고와 서울기록원 로고 위치가 많이 오차가 납니다. - 그 부분을 설명했습니다.
<img width="1498" alt="2017-12-21 10 10 27" src="https://user-images.githubusercontent.com/6022883/34235785-480ffc18-e637-11e7-94a9-d874c9463522.png">



-

**Comment by woonjjang** [comment]
모바일메뉴 펼침시 시작점도 서울시 GNB 고려해서 상단 간극 조절이 필요합니다. 
<img width="381" alt="2017-12-21 10 10 37" src="https://user-images.githubusercontent.com/6022883/34235802-6801b21e-e637-11e7-9ba6-0bd717b23665.png">

**Comment by woonjjang** [comment]
서울시 홈페이지 개편에 따른 GNB 개선 - 관련된 가이드 확인

**Comment by css3studio** [comment]
디자인과 동일하게 회색값 적용하였습니다.
