### ISSUE TITLE
서울사진아카이브 메인 > 검색 기능 추가

### ISSUE THREAD

**Issue by css3studio** [sda17dev/sda-web#173]
http://52.79.195.15/collection/seoul-photo-archive

여기에 변경된 디자인으로 리뉴얼 적용하였습니다.
검색기능만 추가해 주세요.

**Comment by woonjjang** [comment]
<img width="393" alt="default" src="https://user-images.githubusercontent.com/6022883/53508778-c3f10400-3afd-11e9-8bd1-50d74c87ccef.png">
@mozodev 리서치가이드 오른쪽에도 동일한 입력창 적용 부탁드립니다.
