### ISSUE TITLE
문의신청 내용 수정

### ISSUE THREAD

**Issue by css3studio** [sda17dev/sda-web#175]
문의신청 리뉴얼 하여 서버에 적용하였습니다
http://52.79.195.15/about/inquiry

내용 펼쳤을때 보여지는 영역의 내용을 보완해 주시기 바랍니다

**Comment by woonjjang** [comment]
관련되어 기본 스타일로 UL, LI 표현해서 들여쓰기 좀 부탁드리고
전체 링크 스타일 변경한다고 용님한테 얘기 드렸었는데, 클릭 전 상태에 파란색, 밑줄로 링크 임을 확인하도록 해 주세요.
