### ISSUE TITLE
각 페이지 브레드 크럼 항목 점검

### ISSUE THREAD

**Issue by css3studio** [sda17dev/sda-web#176]
최근에 메뉴 항목들의 이름과 구조가 바뀌었는데, 각 페이지의 브레드 크럼에 적용이 안되어 있고 부모항목도 통일되어 있지 않습니다.
전체적으로 점검 부탁합니다.

**Comment by woonjjang** [comment]
소개 브레드크럼 정리

**Comment by woonjjang** [comment]
검색 / 웹 검색으로 검색도구는 분류
뉴스 부분은 브레드크럼 -> 개발쪽에서 지원
컬렉션 브레드크럼 항목 정리
