### ISSUE TITLE
메인 도움말 부분 변경 / 기록 CCL 박스

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#26]
메인_1440px_도움말 부분 변경
기록_CCL

**Comment by css3studio** [comment]
메인_1440px_도움말 부분 변경 완료하였습니다.
확인 바랍니다
html2018/html/00_main.html

**Comment by woonjjang** [comment]
1. 모바일에서 상단 이미지 영역과 여백값을 좀 주시고
2. 이미지 스타일 변경은 디자인팀 최종 확인 후 변경할께요. 확인 !
3. 푸터 위 이메일수집 / 서울사진아카이브 부분은 우선 서울사진아카이브 부분만 남기고 주석처리

**Comment by css3studio** [comment]
네 모바일 모드 스타일링 추가하였습니다.

**Comment by css3studio** [comment]
기록_CCL도 작업하여 커밋하였습니다
