### ISSUE TITLE
[컬렉션] 세부

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#28]
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/ac9896bc1

- 세로로 긴 이미지가 있을 때는 사진 영역을 회색으로 잡고 이미지 대상을 뿌려주세요.(전시 디테일 화면과 비슷)

**Comment by css3studio** [comment]
신규페이지 작업하여 커밋하였습니다

**Comment by woonjjang** [comment]
![2018-08-24 7 16 48](https://user-images.githubusercontent.com/6022883/44580124-b1ef7b00-a7d3-11e8-80e0-ba26bfa99919.png)
샘플 텍스트 입력해 보았습니다. 제목 / 날짜 부분 간격이랑 스타일을 기존 News / 작성일 스타일로 변경해주세요. (날짜 스타일만)

**Comment by woonjjang** [comment]
- 한글, 이미지 수정반영했습니다. (상단 슬라이드 관련 짧게 논의 필요)
- 그룹/아이템 제목과 날짜 간격 조절

**Comment by css3studio** [comment]
그룹/아이템 제목과 날짜 간격등 스타일 조정하여 커밋하였습니다

**Comment by woonjjang** [comment]
55_Collection_detail_2.html로 만들어주세요. 
새로 생겨난 버튼이 상단 이미이 영역 내부에 들어가 있는 버전을 생각했었어요. 

화면 레이아웃 :  https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/ac9896bc1
