### ISSUE TITLE
[CSS]상세검색- 필드 항목 조정

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#29]
43_search_detail -> advanced_search 로 파일 이름 변경

[필드 검색] 영역에 스타일 조정
[생산 년도] 스타일 조정

Clear Form

**Comment by woonjjang** [comment]
http://discovery.nationalarchives.gov.uk/advanced-search

**Comment by woonjjang** [comment]
https://catalog.archives.gov/advancedsearch

**Comment by css3studio** [comment]
43_search_advanced.html 로 바궈도 될까요? 앞에 search가 일종의 그룹 prefix라서요

**Comment by woonjjang** [comment]
이름 괜찮습니다. 
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/aa9df7b72

**Comment by woonjjang** [comment]
주요구분 / 기록 / 기술계층 전체 height 영영을 최대한 좁혀 주세요.  참고 :  https://catalog.archives.gov/advancedsearch
