### ISSUE TITLE
[CSS] 눌러본 기록관련 링크- 다른 스타일 적용

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#30]
- 검색결과 눌러본 링크 다른 스타일 적용
- 검색 / 탐색

**Comment by woonjjang** [comment]
http://discovery.nationalarchives.gov.uk/results/r?_q=seoul

**Comment by css3studio** [comment]
적용하여 커밋하였습니다

**Comment by woonjjang** [comment]
[적용범위]
- 탐색목록
- 검색결과(기록)
- 검색결과(웹)
- 뉴스/컬럼/리서치가이드 목록
