### ISSUE TITLE
[추가 안내 문구] 마우스 Over(예전 스타일에 잡았던 적이 있음.)

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#31]
https://sda17dev.github.io/sda-prototype/html/03_browse_series_detail_view.html#

**Comment by woonjjang** [comment]
![2018-08-27 4 37 40](https://user-images.githubusercontent.com/6022883/44647070-fff4c080-aa17-11e8-86bf-57383716ea81.png)

자주 사용할 예정이어서 도움말 아이콘 혹은 설명글 over시에 링크 포함한 글이 노출될 예정

**Comment by css3studio** [comment]
어느 페이지에 적용이 되는 건가요?

**Comment by css3studio** [comment]
tt01이라는 오브젝트를 만들어 추가하였습니다.
31_browse_view_item.html의 제목 부분에 예시로 추가하였습니다

**Comment by woonjjang** [comment]
확인했습니다.
