### ISSUE TITLE
[CSS - 고객문의 커뮤니티] 목록 / 상세 / 질문작성(모달)

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#39]
디자인 리뷰 끝나면 시작

https://drive.google.com/drive/u/0/folders/1QUoyZM1mMQft2dKjhJ2dvgv2xu1lWQch

**Comment by woonjjang** [comment]
<img width="609" alt="2018-09-14 7 35 14" src="https://user-images.githubusercontent.com/6022883/45545735-2c04a400-b856-11e8-9747-a8965c91c9db.png">

 - 최상단 버튼 이미지 잘림
 - 질문창에서 radio button 선택하면 앞에 아이콘 변경 부탁드려요. (답변 -> 글쓰기, 질문 -> 질문)

**Comment by woonjjang** [comment]
<img width="769" alt="2019-02-08 7 47 08" src="https://user-images.githubusercontent.com/6022883/52474175-12844000-2bdb-11e9-8604-4701c91a1304.png">
질문과 대답 이미지지 반대로 나타나는 현상 (오류)

**Comment by css3studio** [comment]
수정완료하였습니다
