### ISSUE TITLE
사용자 데이터를 이해한다.

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#4]
사용자 DB 관련 연구에도 직접 필요함.

**Comment by sda17dev** [comment]
[G/A]
대부분의 데이터를 측정하는 것은 GA에서 잡고
해당되는 API로 끌어온다. 
주요한  측정 수치를 중심으로 관리단에서 보여준다. 
아이템별 조회수
아이템의 다운로드
동선분석(터널분석)
관리자쪽에서 사용자에게 체크를 해 놓은 페르소나별로 브라우저별로 로그인했을 때 식별되는 방식으로 잡을 수 있다. 

[시스템에서 확인해야 하는 정보 - DB]

일반문의항목 ( 로그인 안 한 사람)
일반문의항목 (로그인 한 사람)
오류신고
요청과 관련된 항목들

[관리자화면의 통계]

담당공무원 주간보고, 월간보고에 필요한 텍스트, 숫자 전달

**Comment by sda17dev** [comment]
[사용자 군별 DB관리 및 확인, 분석]

중요한 것은 어떻게 군을 나누고, 확인하고 싶은것을 정의하는 것이 중요하다. 
회원별 페르소나별로 사용자군별로 확인하는 페이지나 내용이 어떤 것인지 확인한다. 

[이벤트 추적에 대한 시나리오 - 교육, 전시]
웹사이트 메인에 행사, 교육공지, 게시물이 특정 기록과 연관되어 있다고 공지했을 때
기록물까지 도달하는지
이벤트에 대해 실질적 도달을 하는지
어떤 데이터를 확인하고
교훈을 얻는다. 

[CRM처럼]
우리가 진행한 행사에 어떻게 반응했는지 데이터로 갖고 있다. 
8개에 참석 안 하다가 2개 참석하고 후원자가 되었다. 그 행사가 이런 사람과 맞게 표집할 수 있다. 
한 사용자별로 넣고, DB안에서 액티비티 로그를 남겨 놓는다.

**Comment by woonjjang** [comment]
UC 71 | 통계
관리자는 통계 페이지에서 SDA-WEB의 다양한 통계 숫자를 확인한다.

어떤 아이디가 해당 페이지를 언제 클릭했다. (User)
User_ID 가 Entity_ID를 Date에 Act했다. 
- Act - 조회했다. (목록보기, 세부보기)
- Act - 다운로드
- Act - 즐겨찾기  
- Act - Request
- 비고 - json으로 넣는다.(추가로 필요한 부분에 대해서, 소셜미디어 라이크, 공유, 숫자)

어떤 아이디가 해당 페이지를 언제 클릭했다. (User)
Guest User(확인 안 된 User)가 Entity_ID를 Date에 Act했다. 

- Act - 조회했다. 
- Act - 다운로드
- Act - 즐겨찾기
- Act - Request
- 여분 - Json으로 넣는다.((추가로 필요한 부분에 대해서, 소셜미디어 라이크, 공유)

검색관련통계

- User_ID, Anyone이 “검색키워드"를 어떤 날짜에 검색했다.  
- 비고 - 검색엔진에서 제공하는 관련 로그는 서버에 백업한다.

Data Sync 및 카탈로그 통계

- SDA-ENGINE을 통해 동기화된 레코드그룹 N건
- SDA-ENGINE을 통해 동기화된 시리즈 N건
- SDA-ENGINE을 통해 동기화된 파일 N건
- SDA-ENGINE을 통해 동기화된 아이템 N건
- SDA-ENGINE을 통해 동기화된 컴포넌트 N건
- 동기화되면서 변경된 이력이 있는 N건 - 최근 작업 기록 확인

Google Analytics

- 페이지 전체에 적용한다. 
- G/A 스크립트 처리를 위해 사용자 형태별 분류를 통해 페르소나를 나눈다. 
- 데이터를 모은다.

통계와 관련된 구체적인 보고와 시야를 그릴 수 있는 시나리오를 작성한다. 
- 시나리오 1
- 시나리오 2

로그아웃한 사용자가 쿠키동의를 통해서 다운로드 -> 다운로드를 받는 경우의 데이터를 확보한다. 
이관기록이 카탈로그하는 시점에 적용하다.
