### ISSUE TITLE
전시 화면 개선

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#50]
전시쪽
- 아이템 이미지 창에 들어있는 [화면전체] 버튼 추가
-  이미지 다운로드 Block(다운로드 안 되게) 처리 가능한지 
<img width="926" alt="default" src="https://user-images.githubusercontent.com/6022883/45925112-5fc48580-bf4a-11e8-9ba1-e3a324366c23.png">

**Comment by css3studio** [comment]
작업하여 커밋하였습니다
22_introduce02_view.html
