### ISSUE TITLE
about 페이지 상단 이미지 + 오브제 링크

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#62]
http://52.79.195.15/about/organization 에 있는 상단 이미지에 오브제링크 추가부탁드립니다. 
http://52.79.195.15/about 상단이미지 (조직처럼 height값 조정 + 오브제링크)
http://52.79.195.15/helps-for-developer 상단 이미지 추가 + 오브제 링크(사진과 오브제 코멘트는 제가 변경할께요.)
http://52.79.195.15/about/inquiry 상단 이미지 추가 + 오브제 링크(사진과 오브제 코멘트는 제가 변경할께요.)

**Comment by css3studio** [comment]
완료하였습니다

**Comment by woonjjang** [comment]
잘 확인했습니다. 레이아웃이 더 좋아보이네요. ^^
