### ISSUE TITLE
첫 로드시에 슬라이드 이미지가 전부 보이는 현상

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#63]
http://52.79.195.15/collections

로드시에 슬라이드에 포함된 이미지가 보였다가 사라지는데, 
개선이 필요해 보입니다.

**Comment by css3studio** [comment]
이상하네요~ 제 컴에서는 여러번 접속해 보았는데 정상입니다.
테스트 환경이 어떻게 되시나요?

**Comment by woonjjang** [comment]
- MAC > 사파리에서는 그런 현상이 안 보이네요. 
- MAC > 크롬 - 최신 버전 69.0.3497.100(공식 빌드) (64비트)

에서는 refresh 할 때 마다 이런 현상이 있네요.

**Comment by css3studio** [comment]
보완하였습니다

**Comment by woonjjang** [comment]
사파리에서는 괜찮은데,
