### ISSUE TITLE
[전시] VR 1 페이지 + 영상 탑재

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#69]
- 영상촬영완료(10.8)
- 해당내용확인하고,  VR 페이지 Embeded

**Comment by woonjjang** [comment]
- 1차 샘플 HTML테스트 연결

**Comment by mozodev** [comment]
http://52.79.195.15/nexed/index.html

**Comment by woonjjang** [comment]
- VR 영상을 받아서 변경한다. 
- https://krpano.com/
