### ISSUE TITLE
[아이템 컴포넌트] 확대 축소

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#74]
<img width="909" alt="2018-10-21 8 31 12" src="https://user-images.githubusercontent.com/6022883/47278401-b41f5b80-d603-11e8-8981-705f8bbdabe1.png">

확대 축소( HTML 확대 축소 비율 및 액션 조정)

**Comment by woonjjang** [comment]
- 초기화 상태에서 확대 버튼 2번째 눌렀을 때와 3번째 눌렀을 때 1단계 정도만 더 둘 수 있으면 좋겠습니다. (나머지 액션이나 비율들은 좋습니다.

**Comment by css3studio** [comment]
네 작업 다해놓고 보니 플러그인 기능이 그렇더군요. 아직까지 관련 옵션을 찾지 못했습니다. 소스코드를 한번 살펴볼게요
