### ISSUE TITLE
발간번호 신청 및 발행 관리

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#80]
발간번호 목록
발간번호 세부
발간번호 등록

관리 - 발간번호 목록
관리 - 발간번호 세부

발간번호 히스토리 (같은 번호로 변경)

**Comment by woonjjang** [comment]
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/a047aa8bd
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/aeee2c5c4
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/afd2f7913
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/a9042a89b
https://app.moqups.com/slowalk/ddevc2Sl0I/edit/page/a5e794bee

**Comment by woonjjang** [comment]
화면 약간 업데이트 해 놓겠습니다.

**Comment by css3studio** [comment]
발간번호 히스토리 (같은 번호로 변경)는 화면설계서에 없는거 같네요.
발간번호 세부 화면의 변경이력을 가리키는건가요?

**Comment by css3studio** [comment]
발간번호 목록 - 완료
발간번호 등록 - 90%완료, 폼유효성검사 스크립트만 남았습니다.
우선 현재 상태로 배포하고 차주에 계속 작업하겠습니다.
마크업은 변경이 없을거 같으니, 모조님 작업 진행해도 될거 같습니다

**Comment by woonjjang** [comment]
1. 발간번호 수정변경시에 "기존 발간등록번호 검색" 앞에 셀렉트 버튼이 빠졌습니다.(발간번호/기관명)
- 타 서비스에서는 팝업으로 열리는데, 아이템 추가하는 화면을 팝업으로 처리하는 화면을 안 만들고자 조금 고민하고 있었습니다. (아래로 화면이 열리는 방식으로 잡았는데, 보시고 의견주세요.

2. 사용된 텍스트랑 상단 안내 문구는 제가 업데이트 해 놓겠습니다. 

3. 발간번호를 1번 발행받고, 다시 수정할 때도 히스토리를 계속 쌓는 구조입니다. [UC38]정부간행물 발간등록/송부 - 신청내역 보기 페이지 하단에 있는 히스토리를 클릭하면 다른 세부 화면으로 이동합니다. 

4. 세부화면 아래에는 삭제, 수정 버튼이 있는데 로그인 없이 이를 노출하고 있어서 정책확인 후 와이어에 적용해 놓겠습니다.

**Comment by woonjjang** [comment]
<img width="426" alt="2018-11-08 10 49 42" src="https://user-images.githubusercontent.com/6022883/48175217-784bfc00-e34e-11e8-8c24-ea227336e049.png">
모바일쪽 제목 영역이 많이 좁은 것 같습니다.

**Comment by css3studio** [comment]
"타 서비스에서는 팝업으로 열리는데, 아이템 추가하는 화면을 팝업으로 처리하는 화면을 안 만들고자 조금 고민하고 있었습니다. (아래로 화면이 열리는 방식으로 잡았는데, 보시고 의견주세요."

- 살펴보았는데요. 제 생각엔 검색결과에서 아이템 선택시에, 지금 와이어처럼 표가 나타나는게 좀 부자연스러워 보이네요. 일반적인 UX는 선택된 발간번호만 텍스트박스에 넣어주는거고 저도 그게 자연스러워 보입니다.

**Comment by css3studio** [comment]
전체작업완료하여 배포하였습니다

**Comment by woonjjang** [comment]
- 수정삭제 버튼이 추가될 수 있음. 
- 파일 등록 눌렀을 때 레이어가 필요할 수 있음.
