### ISSUE TITLE
기록형태에 따른 컴포넌트 뷰어 개선 및 다양화(PDF)

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#92]
- PDF뷰어
- https://mozilla.github.io/pdf.js/

**Comment by woonjjang** [comment]
도면이미지(큰 이미지 처리)
PDF스캔본 (큰 이미지 처리)

전체보기 적용하면 모질라 뷰어가 열리는 방식이 필요합니다.

**Comment by woonjjang** [comment]
https://mozilla.github.io/pdf.js/ 적용을 안 해주신 것 같아요.

**Comment by css3studio** [comment]
아 일단 html기본 뷰어 넣어달라고 하신걸로 이해했어요. 나오는거 보고 모질라 플러그인 적용해 보자고...
그럼 저거 적용한 버젼 하나 만들어 올리겠습니다
