### ISSUE TITLE
[API] 검색 API 정의 및 작성 시작(내부 / 외부)

### ISSUE THREAD

**Issue by woonjjang** [sda17dev/sda-web#96]
- 도큐사우르스
- WEB쪽 외부 확인에 대한 문서
- 내부에서도 문서를 작성 적용할 수 있는 how to 작성

**Comment by woonjjang** [comment]
https://docs.google.com/document/d/18UNx6gwSp6Dh__pxPwcCm1Eg3jW_3IRzv0NiMt80HNg/edit

**Comment by sda17dev** [comment]
100% - 도큐사우르스 (1/9)

**Comment by sda17dev** [comment]
https://docs.google.com/document/d/1R-t5z_cD3ZUQ2GATQrXnUvcSTQOJInLGQnYq2-1dllE/edit
